version: '3'
services:
  nuxt:
    container_name: Eyecatcher-nuxt
    restart: always
    build: ./nuxt-app-portfolio-eyecatcher-theme/.
    ports:
      - '80:3000'

  images:
    container_name: Eyecatcher-static-file-server
    restart: always
    build: ./static-file-server/.
    ports:
      - '3434:3434'
    volumes:
      - ./static-file-server/public/images/:/usr/src/app/public/images/
