version: '3'
services:
  nuxt:
    build: ./nuxt-app/.
    restart: unless-stopped
    ports:
      - '80:3000'
    volumes:
      - ./nuxt-app/public/:/usr/src/app/public/

        #  static_file_server:
        #    build: ./static-file-server/.
        #    restart: unless-stopped
        #    ports:
        #      - '3434:3434'
        #    volumes:
        #      - ./static-file-server/public/:/usr/src/app/public/
