version: '3'
services:
  #  db:
  #    container_name: PW-mongo-db
  #    image: mongo
  #    ports:
  #      - '27017:27017'
  #    volumes:
  #      - data:/data/db
  #
  #  api:
  #    container_name: PW-node-api
  #    restart: always
  #    build: .
  #    ports:
  #      - '3000:3000'
  #    links:
  #      - "db:mongo"
  #    volumes:
  #      - ./frontend:/usr/src/app
  #
  strapi:
    image: strapi/strapi:3.6.8
    container_name: strapi_cms
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./backend/app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3306:3306'


volumes:
  data:
  mysql:

