version: '3'
services:
  db:
    container_name: PW-mongo-db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db

  api:
    container_name: PW-node-api
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - "db:mongo"
    volumes:
      - .:/usr/src/app

volumes:
  data:
