services:
  nuxt:
    build: ./nuxt-app/.
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./nuxt-app/public/project/:/usr/src/app/.output/public/project/
      - ./nuxt-app/public/blog/:/usr/src/app/.output/public/blog/
      - ./nuxt-app/public/GeertRoks-aboutme.png:/usr/src/app/.output/public/GeertRoks-aboutme.png
